version: "2"
services:
  identidock:
  network_mode: bridge
    build:
      context: ../identidock
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - "dnmonster"
      - "redis"

  dnmonster:
    image: amouat/dnmonster:1.0
    network_mode: bridge

  redis:
    image: redis:3.0
    network_mode: bridge
